# Site settings
title: thethingiswaiter
header-img: "img/Xacebook.jpg"
tagline: "cn"  
description: "姚衍|惺相近，惜相远"  
baseurl: ""
url: "http://thethingiswaiter.com"  

# About/contact
owner: 
  name: " thethingiswaiter"
  email: 13125996730@163.com
  bio: "必须喜欢学习"

# Data
gavatar: http://openmindclub.qiniudn.com/omt/GavatarCNFeat.png
favicon: img/favicon.png

douban_username:  姚衍
github_username: thethingiswaiter
facebook_username: 
weibo_username:
zhihu_username: 姚衍

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "姚衍"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus
  duoshuo :
    short_name : 姚衍
  disqus :
      short_name : 姚衍

# Analytics and webmaster tools stuff goes here
google_analytics: UA-80884545-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
